[package]
name = "outliving-deref"
version = "0.0.0"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2021"
description = "Traits for types when dereferenced may outlive their values"
documentation = "https://docs.rs/outliving-deref"
repository = "https://github.com/yescallop/outliving-deref"
license = "MIT"
keywords = ["deref"]
categories = ["rust-patterns"]

[features]
default = ["std"]
std = []

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
