[package]
name = "borrow-or-expose"
version = "0.0.0"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2021"
description = "Traits for either borrowing from or exposing a reference from a value"
documentation = "https://docs.rs/borrow-or-expose"
repository = "https://github.com/yescallop/borrow-or-expose"
license = "MIT"
categories = ["rust-patterns"]

[features]
default = ["std"]
std = []

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
